version: '3'
services:
    apache:
        container_name: apache
        image: php:7.4.2-apache-buster
        depends_on: 
            - mysql
        ports:
            - 8080:80
        volumes: 
            - ./apache/codes:/var/www/html


    mysql: 
        container_name: mysql
        image: mysql:8.0.19
        environment: 
            MYSQL_ROOT_PASSWORD: 1UGuIi45mXkbsVUBb&NScp#Kij7
            MYSQL_DATABASE: optest
            MYSQL_USER: joff
            MYSQL_PASSWORD: goreal
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8082:80
        environment: 
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        depends_on: 
            - mysql
