version: '3'

services:
   mysql:
     container_name: mysql
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
     restart: always
     environment: 
       MYSQL_ROOT_PASSWORD: JQHSBDJGQJKS
       MYSQL_DATABASE: wordpress
       MYSQL_USER: user
       MYSQL_PASSWORD: JQHSBDJGQJKS

   wordpress:
     container_name: wordpress
     depends_on:
       - mysql
     build: ./wordpress
     ports:
       - "127.0.0.1:8085:80"
     restart: always
     volumes:
       - ./wordpress/www:/var/www/html
     environment:
       - APACHE_DOCUMENT_ROOT=/var/www/html


